-- MySQL Script generated by MySQL Workbench
-- Sat Mar 30 19:18:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema minedexf_tp3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minedexf_tp3
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `minedexf_tp3` DEFAULT CHARACTER SET utf8 ;
USE `minedexf_tp3` ;

-- -----------------------------------------------------
-- Table `minedexf_tp3`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minedexf_tp3`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `usager` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  `action` DATETIME NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minedexf_tp3`.`groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minedexf_tp3`.`groupe` (
  `id_groupe` INT NOT NULL AUTO_INCREMENT,
  `admin` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_groupe`),
  INDEX `fk_groupe_client1_idx` (`admin` ASC),
  CONSTRAINT `fk_groupe_client1`
    FOREIGN KEY (`admin`)
    REFERENCES `minedexf_tp3`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minedexf_tp3`.`liste_groupe_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minedexf_tp3`.`liste_groupe_client` (
  `id_client_fk` INT NOT NULL,
  `id_groupe_fk` INT NOT NULL,
  PRIMARY KEY (`id_client_fk`, `id_groupe_fk`),
  INDEX `fk_client_has_groupe_groupe1_idx` (`id_groupe_fk` ASC),
  INDEX `fk_client_has_groupe_client_idx` (`id_client_fk` ASC),
  CONSTRAINT `fk_client_has_groupe_client`
    FOREIGN KEY (`id_client_fk`)
    REFERENCES `minedexf_tp3`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_groupe_groupe1`
    FOREIGN KEY (`id_groupe_fk`)
    REFERENCES `minedexf_tp3`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minedexf_tp3`.`fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minedexf_tp3`.`fichier` (
  `id_fichier` INT NOT NULL AUTO_INCREMENT,
  `id_groupe_fk` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_fichier`),
  INDEX `fk_fichier_groupe1_idx` (`id_groupe_fk` ASC),
  CONSTRAINT `fk_fichier_groupe1`
    FOREIGN KEY (`id_groupe_fk`)
    REFERENCES `minedexf_tp3`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minedexf_tp3`.`invitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minedexf_tp3`.`invitation` (
  `id_invitation` INT NOT NULL AUTO_INCREMENT,
  `id_groupe_fk` INT NOT NULL,
  `id_client_fk` INT NOT NULL,
  PRIMARY KEY (`id_invitation`),
  INDEX `fk_invitation_groupe1_idx` (`id_groupe_fk` ASC),
  INDEX `fk_invitation_client1_idx` (`id_client_fk` ASC),
  CONSTRAINT `fk_invitation_groupe1`
    FOREIGN KEY (`id_groupe_fk`)
    REFERENCES `minedexf_tp3`.`groupe` (`id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invitation_client1`
    FOREIGN KEY (`id_client_fk`)
    REFERENCES `minedexf_tp3`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
