//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serveur
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.groupe = new HashSet<groupe>();
            this.invitation = new HashSet<invitation>();
            this.groupe1 = new HashSet<groupe>();
        }
    
        public int id_client { get; set; }
        public string nom { get; set; }
        public string usager { get; set; }
        public string motdepasse { get; set; }
        public Nullable<System.DateTime> action { get; set; }
    
        public virtual ICollection<groupe> groupe { get; set; }
        public virtual ICollection<invitation> invitation { get; set; }
        public virtual ICollection<groupe> groupe1 { get; set; }
    }
}
