//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serveur
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupe
    {
        public groupe()
        {
            this.fichier = new HashSet<fichier>();
            this.invitation = new HashSet<invitation>();
            this.client1 = new HashSet<client>();
        }
    
        public int id_groupe { get; set; }
        public int admin { get; set; }
        public string nom { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<fichier> fichier { get; set; }
        public virtual ICollection<invitation> invitation { get; set; }
        public virtual ICollection<client> client1 { get; set; }
    }
}
