//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class minedexf_tp3Entities : DbContext
    {
        public minedexf_tp3Entities()
            : base("name=minedexf_tp3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<client> client { get; set; }
        public DbSet<fichier> fichier { get; set; }
        public DbSet<groupe> groupe { get; set; }
        public DbSet<invitation> invitation { get; set; }
    }
}
